const data = {
    annoyed: [
        "you always knew how to push my buttons.",
        "if the story's over why am I still writing pages?",
        "i mean this is exhausting, you know?",
        "i threw my phone across the room.",
        "i complained the whole way there.",
    ],
    defeated: [
        "i should've known.",
        "horrified looks from everyone in the room.",
        "i think there's been a glitch, a brief interruption, a slight malfunction.",
        "i knew you were trouble when you walked in, so shame on me now.",
        "sometimes giving up is the strong thing.",
        "the more that you say the less I know.",
        "got nothing in my brain, that's what people say.",
        "it's 2 a.m. and I'm cursing your name.",
    ],
    oops: [
        "you say, I don't understand, and I say, I know you don't.",
        "it's me, hi, I'm the problem it's me.",
        "is it too soon to do this yet? Cause I know that it's delicate.",
        "i can fix him, no really, I can.",
        "all I feel in my stomach is butterflies.",
        "long story short, it was a bad time.",
    ],
    proud: [
        "karma is the breeze in my hair on the weekend.",
        "you are the best thing that's ever been mine.",
        "long live all the magic we made.",
        "let's hear the applause.",
        "when I walk in the room I can still make the whole place shimmer.",
        "it was all by design, cause I'm a mastermind.",
        "it's like snow at the beach, weird but it was beautiful.",
        "who's afraid of little old me? Well, you should be.",
        "i don't know how it gets better than this.",
    ],
    relaxed: [
        "and by morning gone was any trace of you, I think I am finally clean.",
        "there's a dazzling haze, a mysterious way about you dear.",
        "the devil's in the details, but you got a friend in me.",
        "you're on your own, kid, you always have been.",
        "all there's left to do is run.",
        "it's gonna be alright, I did my time.",
    ],
    sad: [
        "i might be okay but I'm not fine at all.",
        "am I allowed to cry?",
        "maybe it's me and my blind optimism to blame.",
        "i might just die, it would make no difference.",
        "wish you could go back and tell yourself what you know now.",
    ],
    yolo: [
        "they say I did something bad, but why's it feel so good?",
        "i cry a lot but I am so productive, it's an art.",
        "i could show you incredible things, magic, madness, heaven, sin.",
        "no rules in breakable heaven.",
        "when we go crashing down, we come back every time.",
    ],
} as const;

export default data;
